# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-06 18:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blog_entry',
            new_name='BlogEntry',
        ),
    ]
