# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-06 20:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160806_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogentry',
            name='author',
        ),
        migrations.DeleteModel(
            name='BlogEntry',
        ),
    ]
