# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-06 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='additional_data',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='expiry_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='subtitle',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
