# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-06 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django_markdown.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20161106_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='section',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='text',
            field=django_markdown.models.MarkdownField(),
        ),
    ]
