# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-06 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20161106_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='anchor',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
